import { useState, useEffect, useCallback } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import {
  AppConfig,
  UserSession,
  showConnect,
  openContractCall,
} from '@stacks/connect';
import {
  uintCV,
  stringUtf8CV,
  hexToCV,
  cvToHex,
  callReadOnlyFunction,
  makeContractCall,
  broadcastTransaction,
  AnchorMode,
  NonFungibleConditionCode,
  FungibleConditionCode,
  createAssetInfo,
  makeStandardNonFungiblePostCondition,
  makeStandardSTXPostCondition,
  bufferCVFromString,
  standardPrincipalCV,
} from '@stacks/transactions';
import useInterval from "@use-it/interval";
import { StacksMocknet, StacksTestnet, StacksMainnet } from '@stacks/network';

const Home: NextPage = () => {
  const appConfig = new AppConfig(['publish_data']);
  const userSession = new UserSession({ appConfig });

  const [price, setPrice] = useState(5); // pre-fill a fixed price, can be changed to ""
  const handlePriceChange = (e) => { setPrice(e.target.value) };

  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [userData, setUserData] = useState({});
  const [loggedIn, setLoggedIn] = useState(false);

  // Set up the network and API
  const network = new StacksTestnet();
  // for mainnet, use `StacksMainnet()`
  // for devnet, use `StacksMocknet()`

  // call the mint function from frontend
  const mint = async () => {
    // the address of the NFT contract generated by clarinet integrate
    const assetAddress = 'ST2NC54N30J95AHB55W6VY3MF9X4G07F4XCPVYKGD'
    
    const functionArgs = [
      standardPrincipalCV(
        userSession.loadUserData().profile.stxAddress.testnet
      ),
    ]

    // Add post conditions here
    const postConditionAddress =
      userSession.loadUserData().profile.stxAddress.testnet;
    const nftPostConditionCode = NonFungibleConditionCode.Owns;
    const assetContractName = 'partage-v1'
    const assetName = 'fraction'
    const tokenAssetName = bufferCVFromString('fraction')
    const nonFungibleAssetInfo = createAssetInfo(
      assetAddress,
      assetContractName,
      assetName
    )
    const stxConditionCode = FungibleConditionCode.LessEqual;
    const stxConditionAmount = price * 1000000; // price converted in microstacks
    const postConditions = [
      makeStandardNonFungiblePostCondition(
      postConditionAddress,
      nftPostConditionCode,
      nonFungibleAssetInfo,
      tokenAssetName
      ),
      makeStandardSTXPostCondition(
      postConditionAddress,
      stxConditionCode,
      stxConditionAmount
      ),
    ];

    const options = {
      contractAddress: assetAddress,
      contractName: 'partage-v1',
      functionName: 'mint-nft',
      functionArgs,
      //senderKey: 'b244296d5907de9864c0b0d51f98a13c52890be0404e83f273144cd5b9960eed01',
      //validateWithAbi: true,
      network,
      // Don't forget to pass the created post conditions here
      postConditions,
      //anchorMode: AnchorMode.Any,
      appDetails: {
        name: 'Partage',
        icon: '',
      },
      onFinish: (data: any) => {
        console.log(data)
      },
    };

    //const transaction = await makeContractCall(options);
    //const broadcastResponse = await broadcastTransaction(transaction, network);
    //const txId = broadcastResponse.txid;

    await openContractCall(options);
  };

  // function to connect wallet (web3 login ^^)
  function authenticate() {
    showConnect({
      appDetails: {
        name: 'Partage',
        icon: '',
      },
      redirectTo: '/',
      onFinish: () => {
        window.location.reload()
      },
      userSession,
    });
  }

  useEffect(() => {
    if (userSession.isSignInPending()) {
      userSession.handlePendingSignIn().then((userData) => {
        setUserData(userData)
      })
    } else if (userSession.isUserSignedIn()) {
      setLoggedIn(true)
      setUserData(userSession.loadUserData())
    }
  }, []);

  return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2">
      <Head>
        <title>Partage</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full flex-1 flex-col items-center justify-center px-20 text-center">
        <h1 className="text-6xl font-bold">Shared NFT utilities</h1>
        <p className="mt-4 w-full text-xl md:w-1/2">
          Partage-v1 contains public functions to mint, burn, transfer, fractionalize NFTs, list and unlist fractions for sale, buy, transfer and burn fractions.
        </p>

        <div className="mt-6 flex max-w-4xl flex-wrap items-center justify-around sm:w-full">
          {loggedIn ? (
            <>
              <p>
                Buy a fraction for
                <input
                  className="p-6 border rounded mx-2"
                  type="number"
                  value={price}
                  onChange={handlePriceChange}
                />{" "}
                STX
              </p>
              <button
                onClick={() => mint()}
                className="rounded bg-indigo-500 p-4 text-2xl text-white hover:bg-indigo-700"
              >
                Mint
              </button>
            </>
          ) : (
            <button
              className="bg-white-500 mb-6 rounded border-2 border-black py-2 px-4 font-bold hover:bg-gray-300"
              onClick={() => authenticate()}
            >
              Connect Wallet
            </button>
          )}
        </div>
      </main>
    </div>
  );
}

export default Home